version: '3'

env:
  PROTO_SRC: 'proto'
  PROTO_FILES: 'proto/*.proto'
  PROTO_OUT: './protogen/'

tasks:
  go:
    cmds:
      - go run main.go
  proto:
    cmds:
      - protoc -I $PROTO_SRC $PROTO_FILES --go_out=$PROTO_OUT --go_opt=paths=source_relative --go-grpc_out=$PROTO_OUT --go-grpc_opt=paths=source_relative --grpc-gateway_out=$PROTO_OUT --grpc-gateway_opt=paths=source_relative --grpc-gateway_opt=generate_unbound_methods=true
  pgx:
    cmds:
      - CONFIG_PATH=config/pgx_config.yaml go run practices/pgx_practice/main/main.go
  pgx-migration:
    # goose -dir migration/pgx_goose_migration create name_file sql
    cmds:
      - export GOOSE_DRIVER=postgres
      - export GOOSE_DBSTRING=postgresql://eer0:hahaha1234@localhost:5500/golang-practice?sslmode=disable
      - export GOOSE_MIGRATION_DIR=migration/pgx_goose_migration
      - goose up
